name: Ubuntu CI Test

on:
  push:
    branches: [ main, master, dev ]
  pull_request:
    branches: [ main, master, dev ]

# Aggiungi esplicitamente i permessi
permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Usa un PAT invece del GITHUB_TOKEN predefinito
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libeigen3-dev gcovr ccache doxygen

    - name: Prepare build directory
      run: |
        make prepare

    - name: Configure CMake
      run: |
        cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Debug -DENABLE_COVERAGE=On -DUSE_CPM=ON
        # Add _deps to the exclude list in codecov.yml
        echo "ignore:" >> codecov.yml
        echo "  - \"_deps/**/*\"" >> codecov.yml

    - name: Build and run tests
      run: |
        cmake --build build --config Debug -j4
        cd build
        ctest -V .

    - name: Generate coverage report
      run: |
        cd build
        # Create coverage directory
        mkdir -p coverage
        # Run gcovr with explicit exclusion of _deps directory and ignoring specific gcov errors
        gcovr --root=.. -r ../src --object-directory=. --html coverage/index.html --html-details --cobertura coverage/coverage.cobertura.xml --exclude-directories "../_deps" --exclude-directories "../.cpmcache" --exclude "../tests/*" --gcov-ignore-errors=no_working_dir_found --print-summary

    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: build/coverage/coverage.cobertura.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '60 80'

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md

    - name: Commit Coverage Report to Repository
      if: github.event_name == 'push'
      run: |
        # Copy the coverage report to a location in the repository
        cp code-coverage-results.md coverage-report.md

        # Configure Git
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

        # Add and commit the file
        git add coverage-report.md
        git commit -m "Update code coverage report [skip ci]" || echo "No changes to commit"

        # Push changes
        git push
